### ISSUE TITLE
Exposed load balancer port

### ISSUE THREAD

**Issue by AndKram** [dask/helm-chart#11]
Is the Dask task schduler service exposed as a public IP / port by using a Kubernetes load balancer service? Possible security implications of this on (say cloud) deployments needs investigation.

**Comment by lukejpreston** [comment]
I saw this too, in your values.yaml you can do this which stops it being a load balancer

```yaml
dask:
  jupyter:
    enabled: false
  scheduler:
    serviceType: ClusterIP
```
