### ISSUE TITLE
Adding ExtraConfig in JupyterHub Results in Error

### ISSUE THREAD

**Issue by rileyhun** [dask/helm-chart#114]
I tried adding extraConfig options to the Jupyterhub config using the Daskhub helm chart yaml file, but it resulted in the error shown below. 

**What happened**:

I got this error:

`coalesce.go:196: warning: cannot overwrite table with non table for extraConfig (map[])`

and the jupyterhub public proxy service wouldn't start

**What you expected to happen**:
I expected the service to start when I add extraConfig options to the Jupyterhub config

**Minimal Complete Verifiable Example**:

```bash
jupyterhub:
  hub:
    extraConfig: |
      c.JupyterHub.hub_connect_ip = '0.0.0.0'
      c.JupyterHub.bind_url = 'http://127.0.0.1:8000'
```

```bash
helm upgrade --install \
    --namespace  ${NAMESPACE} \
    --values config.yaml \
    --values=secrets.yaml \
    --version=4.4.1 \
    ${RELEASE} \
    dask/daskhub
```

**Comment by jacobtomlinson** [comment]
@rileyhun as daskhub uses the [map style config](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/advanced.html?highlight=extra%20config#hub-extraconfig) for `extraConfig` you must also do the same.

```yaml
jupyterhub:
  hub:
    extraConfig: 
      01-rileyhun-config: |
        c.JupyterHub.hub_connect_ip = '0.0.0.0'
        c.JupyterHub.bind_url = 'http://127.0.0.1:8000'
```
