### ISSUE TITLE
dask worker / scheduler preload script

### ISSUE THREAD

**Issue by sanlanka** [dask/helm-chart#115]
There is no way to include [preload](https://docs.dask.org/en/latest/setup/custom-startup.html) path / script to the existing chart as an option or through values.yaml. If I needed to add custom scripts or path to my workers to preload, there should be an option. Is this something that is requested or is there a work around?

**Comment by jacobtomlinson** [comment]
Thanks for pointing this out @sanlanka. I've added this configuration option so you can do something like this.

```yaml
scheduler:
  extraArgs: 
    - --preload
    - scheduler-setup.py

worker:
  extraArgs: 
    - --preload
    - worker-setup.py
```
