### ISSUE TITLE
Support aws IAM role in the chart.

### ISSUE THREAD

**Issue by sanlanka** [dask/helm-chart#121]
For access control, dask workers should be able to use IAM role instead of security credentials added as env variables like so

```
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    name: aws-cli
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::ACCOUNTID:role/S3-BUCKET-Role
spec:
  containers:
  - image: fstab/aws-cli
    command:
      - "/home/aws/aws/env/bin/aws"
      - "s3"
      - "ls"
      - "some-bucket"
    name: aws-cli
```
