### ISSUE TITLE
Allow tuning memory configuration parameters on workers 

### ISSUE THREAD

**Issue by sanlanka** [dask/helm-chart#134]
We will need a way to set memory parameters on a worker that cane be usually done in the config as such.
```
distributed:
  worker:
    # Fractions of worker memory at which we take action to avoid memory blowup
    # Set any of the lower three values to False to turn off the behavior entirely
    memory:
      target: 0.60  # target fraction to stay below
      spill: 0.70  # fraction at which we spill to disk
      pause: 0.80  # fraction at which we pause worker threads
      terminate: False  # fraction at which we terminate the worker

```

**Comment by jacobtomlinson** [comment]
Dask config can be set via environment variables too. Which the chart supports.

```yaml
values.yaml

worker:
  env:
    DASK_DISTRIBUTED__WORKER__MEMORY__TARGET: "0.6"
    DASK_DISTRIBUTED__WORKER__MEMORY__SPILL:  "0.7"
    DASK_DISTRIBUTED__WORKER__MEMORY__PAUSE:  "0.8"
    DASK_DISTRIBUTED__WORKER__MEMORY__TERMINATE:  "false"
```
You can find [a tool](https://docs.dask.org/en/latest/configuration.html) on the docs page to convert between YAML and environment variable formats.
