### ISSUE TITLE
Add additional worker groups

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/helm-chart#221]
Inspired by dask/dask-kubernetes#384 it would be awesome to support multiple worker groups in the Helm Chart.

Currently the chart creates one deployment for workers, but there is nothing to stop us from creating multiple deployments with different resources. For example we could add an additional GPU or high memory deployment which Dask can select via task annotations.

Today the worker is configured like this

```yaml
worker:
  name: worker
  image:
    repository: "daskdev/dask"  
    tag: 2022.1.0 
  replicas: 3 
  resources: 
    requests:
      cpu: 1
      memory: 3G
```

This could be turned into a list to support multiple groups.

```yaml
worker_groups:
  - name: cpu
    image:
      repository: "daskdev/dask"  
      tag: 2022.1.0 
    replicas: 3 
    resources: 
      limits:
        cpu: 1
        memory: 3G
        nvidia.com/gpu: 1
      requests:
        cpu: 1
        memory: 3G
        nvidia.com/gpu: 1
  - name: gpu
    image:
      repository: "daskdev/dask"  
      tag: 2022.1.0 
    replicas: 2
    resources: 
      requests:
        cpu: 4
        memory: 12G
        nvidia.com/gpu: 1
```

Or perhaps to maintain backward compatibility we could do something like this.

```yaml
worker:
  name: worker
  image:
    repository: "daskdev/dask"  
    tag: 2022.1.0 
  replicas: 3 
  resources: 
    requests:
      cpu: 1
      memory: 3G

additional_worker_groups:
  - name: gpu
    image:
      repository: "daskdev/dask"  
      tag: 2022.1.0 
    replicas: 2
    resources: 
      requests:
        cpu: 4
        memory: 12G
        nvidia.com/gpu: 1
```

Hopefully this couple be implemented by reusing the current worker deployment template and just recycling it over and over.

**Comment by ljstrnadiii** [comment]
Thanks for being so receptive! I am looking forward to this.

**Comment by jacobtomlinson** [comment]
Closed in #222

**Comment by jacobtomlinson** [comment]
This should be available now @ljstrnadiii.

For configuring an additional group with high memory you want some config like

```yaml
additional_worker_groups:
  - name: high-mem
    extraArgs:
      - --resources
      - "MEMORY=100e9"
    resources:
      limits:
        memory: 100G
      requests:
        memory: 100G
```

Scaling is not supported via the `HelmCluster` class though, you'll need to scale with `kubectl`.
