### ISSUE TITLE
[BUG] Using a hostname to expose Jupyter causes Helm Render to fail

### ISSUE THREAD

**Issue by DerTiedemann** [dask/helm-chart#239]
**What happened**:
When using a non-nil host value for the ingress that exposes the jupyter notebook, the chart fails to render.
```
Error: YAML parse error on dask/templates/dask-jupyter-ingress.yaml: error converting YAML to JSON: yaml: line 20: mapping values are not allowed in this context
```

**What you expected to happen**:
https://github.com/dask/helm-chart/blob/0b2c263cd507adcf7a3dda0e0a091d792043859c/dask/templates/dask-jupyter-ingress.yaml#L20-L23
L21 introduced in #210 has a trailing `-` that causes all white space to be "chomped" e.g. removed, resulting in invalid yaml. (e.g the error mentioned above)

**Minimal Complete Verifiable Example**:
`values.yaml`
```yaml 
jupyter:
  name: jupyter # Jupyter name.
  enabled: true # Enable/disable the bundled Jupyter notebook.
  rbac: true
  ingress:
    enabled: true # Enable ingress.
    tls: true # Ingress should use TLS.
    secretName: dask-jupyter-tls
    hostname: "jupyter.example.com" # Ingress hostname.
```

**Anything else we need to know?**:
PR with a fix #
