### ISSUE TITLE
SSL error when having https enabled with manual certificates in jupyterhub side. 

### ISSUE THREAD

**Issue by MarineChap** [dask/helm-chart#319]
Dear, 
We have a daskhub server on a supercomputer in our lab. We are based on the latest helm chart ( daskhub-2022.6.0  version 2022.6.1)
https on jupyterhub is enabled through manual certificate and it seems dask cannot success to communicate together.

config :
```
jupyterhub:
  hub:
    services:
      dask-gateway:
        apiToken: secret1
  proxy:
    https:
      enabled: true
      hosts:
         - 10.86.1.95
      type: secret
      secret:
         name: example-tls
    traefik: 
      networkPolicy: 
        enabled: False


dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: secret1

```
Now when I try to create a dask cluster in my jupyterhub session, I am having a ssl error. 
```python
from dask_gateway import Gateway
gateway = Gateway()
cluster = gateway.new_cluster() 
```

Error: 
```
ClientConnectorCertificateError: Cannot connect to host proxy-public:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]
```

Note that if I deactivate https in jupyterhub and work only with http everything is running correctly. So, I think there is a bug somewhere when using manual authentification. 

Any idea for me ? Thanks
