### ISSUE TITLE
Kernel not starting on EKS

### ISSUE THREAD

**Issue by JulianWgs** [dask/helm-chart#52]
Hello,

 I deployed this EKS cluster with eksctl:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster-01
  region: eu-central-1
  version: "1.14"

availabilityZones: ["eu-central-1a", "eu-central-1b","eu-central-1c"]

nodeGroups:
  - name: test-nodes
    instanceType: c5.large
    volumeSize: 30
    desiredCapacity: 2
    privateNetworking: true
    maxPodsPerNode: 10
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
```

and then I installed dask via helm on the cluster. I've only changed the the passwort in the configuration file.

CHART: dask-4.1.6
APP VERSION: 2.11.0

I can connect to the jupyter lab, create a notebook, save it, but no kernel is able to start (no execution or syntax highlighting).

I'd be glad for any help :)
