### ISSUE TITLE
error on helm upgrade

### ISSUE THREAD

**Issue by jgerardsimcock** [dask/helm-chart#7]
Running `helm upgrade {deployment_name} dask/dask -f worker-config.yml` returns following error

`
Error: UPGRADE FAILED: render error in "dask/templates/dask-worker-deployment.yaml": template: dask/templates/dask-worker-deployment.yaml:36:58: executing "dask/templates/dask-worker-deployment.yaml" at <.Values.workers.defa...>: can't evaluate field default_resources in type interface {}
`

This looks like its pointing to line 33 in the [values.yml](https://github.com/dask/helm-chart/blob/master/dask/values.yaml) file. 

my helm version is 2.8.1. I am not sure if that matters. 

Perhaps related to [this](https://github.com/kubernetes/helm/issues/1579)

**Comment by mrocklin** [comment]
Can you try with stable/dask and report if that also fails? (they should be
similar)

**Comment by jgerardsimcock** [comment]
This works `helm install stable/dask --name=dask  -f worker-config.yml`. Where `worker-config.yml` is just some additional libraries for the workers and notebook.

**Comment by BrendanMartin** [comment]
Hey, I'm actually running into this issue right now. I get the same Error message, and my yaml looks like:

```
worker:
  replicas: 8
  limits:
    cpu: 2
    memory: "4G"
  pipPackages: >-
    git+https://github.com/gcsfs/gcsfs.git

jupyter:
  pipPackages: >-
    git+https://github.com/gcsfs/gcsfs.git
```

I'm using `helm upgrade <NAME> stable/dask -f C:/Users/Brendan/helm/config.yml`
