### ISSUE TITLE
Dashboard does not display all the workers

### ISSUE THREAD

**Issue by vinhdiesal** [dask/helm-chart#73]
I received advice from the `dask-gateway` forum to use the `dask helm chart` instead. 
I managed to install the helm chart on `two nodes` per a revised `values.yaml` file to have 10 `dask workers` total.
On the `kubernetes dashboard` I was able to see 10 workers installed on the two nodes, however the Dask dashboard only displays 5 workers. How do I display all the workers so I can view my resources when I perform computing? 
Thanks, 

Vinh

**Comment by vinhdiesal** [comment]
I reinstalled the helm chart to the newest version released today and not it only installs on one node (which is the remote node) even though I specified 10 workers. How do I get it back to two nodes and also, how do I connect to the dashboard.

**Comment by jacobtomlinson** [comment]
If only 5 workers are displaying this is likely because they have not successfully connected to the scheduler. What do the logs show?

When you install a helm chart it creates resources on the whole Kubernetes cluster. There is no concept of installing on specific nodes. If you are only seeing workers on one node this likely shows that the other node is having problems.

How did you create your kubernetes cluster?

**Comment by vinhdiesal** [comment]
I'm currently using `microk8s` to create a `kubernetes` cluster between my local machines. I chose `microk8s` because you can get setup `k8` very quickly. The commands/dashboards are the same.
Here is how I create my `kubernetes` cluster: 
I installed `microk8s` on all machines, then on the master I performed a `microk8s add-node`
On the remote machines I would paste in the `micro join <token>` command and then all the nodes show up on the cluster. 
I install the helm chart by modifying the values.yaml downloaded from github. 
My `helm` installation is the following: `helm install -n my-dask --namespace dask-network dask/dask --version 4.1.11 -f `values.yaml`:
```
worker:
  name: worker
  image:
    repository: "daskdev/dask"
    tag: 2.18.1
    pullPolicy: IfNotPresent
    dask_worker: "dask-cuda-worker"
    dask_worker: "dask-worker"
    pullSecrets:
    #  - name: regcred
  replicas: 10
  default_resources:  # overwritten by resource limits if they exist
    cpu: 1
    memory: "4GiB"
  env:
```
Please help.







I modified the `values.yaml` with the intention of 5 dask-cuda-workers on one machine and 5 dask-workers on the other machine. 
`values.yaml`





Sometimes I can get it on both nodes, most times I get in on one node, I'm not sure how to set it up so I can get it everytime.

**Comment by jacobtomlinson** [comment]
Thanks for the extra information. It sounds like the Dask Helm chart is installing correctly and that the problem you are experiencing are related to microk8s.

Kubernetes will handle resource allocation for you and will decide where to place workers. This may result in all workers being on one node, or both nodes. Kubernetes will just assign workers where it thinks they would fit within the cluster. 

The only recommendation I have is to ensure you are setting the resources section to match your `default_resources` as Kubernetes will use these values to decide where to place workers.

```yaml
resources:
  limits:
    cpu: 1
    memory: 4G
  requests:
    cpu: 1
    memory: 4G
```
