### ISSUE TITLE
Dask Cuda Worker

### ISSUE THREAD

**Issue by vinhdiesal** [dask/helm-chart#74]
I have two machines with NVIDIA GPUS and a iMAC in a `kubernetes` cluster. I'm trying to spread out the workers so I can have a mix of `dask cuda workers` and `dask workers`, but I'm not getting the `dask cuda workers` on any of the nodes. 
I modified the `values.yaml` file as follows to get a dask cuda worker
```
worker:
  name: worker
  image:
    repository: "daskdev/dask"
    tag: 2.19.0
    pullPolicy: IfNotPresent
    dask_worker: "dask-cuda-worker"
    dask_worker: "dask-worker"
    pullSecrets:
    #  - name: regcred
  replicas: 10
  default_resources:  # overwritten by resource limits if they exist
    cpu: 1
    memory: "4GiB"
  env:
  #  - name: EXTRA_APT_PACKAGES
  #    value: build-essential openssl
  #  - name: EXTRA_CONDA_PACKAGES
  #    value: numba xarray -c conda-forge
  #  - name: EXTRA_PIP_PACKAGES
  #    value: s3fs dask-ml --upgrade
  resources: {}
  #  limits:
  #    cpu: 1
  #    memory: 3G
  #    nvidia.com/gpu: 1
  #  requests:
  #    cpu: 1
  #    memory: 3G
  #    nvidia.com/gpu: 1
  tolerations: []
  nodeSelector: {}
  affinity: {}
  securityContext: {}
  # serviceAccountName: ""
  # port: ""
  #  this option overrides "--nthreads" on workers, which defaults to resources.limits.cpu / default_resources.limits.cpu
  #  use it if you need to limit the amount of threads used by multicore workers, or to make workers with non-whole-number cpu limits
  # threads_per_worker: 1 
```
