### ISSUE TITLE
Add option for volume mounts

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/helm-chart#76]
It would be great to be able to configure volume mounts on the notebook and workers. This way if they need to access some network resource or other Kubernetes volume type they can.

Inspired by #75

**Comment by tonycpsu** [comment]
@jacobtomlinson : I see this issue is still open.  Was this implemented properly in #102?  Running the latest release (2021.4.0), I tried adding `mounts:` sections to my daskhub values.yaml file, but the mounts aren't showing up in the pods.

Relevant sections of my config:

```
jupyter:
  mounts:
    volumes:
      - name: project
        persistentVolumeClaim:
            claimName: claim-name
    volumeMounts:
        - name: data
          mountPath: /data


worker:
  mounts
    volumes:
      - name: project
        persistentVolumeClaim:
            claimName: claim-name
    volumeMounts:
        - name: data
          mountPath: /data
```

**Comment by jacobtomlinson** [comment]
@tonycpsu that looks right to me.

Have you tried running `helm template --debug` or `helm get manifest` and inspected the manifests which were rendered to see if the mounts are correct there?

**Comment by tonycpsu** [comment]
Not yet, no.  I confess to being a bit of a Helm noob, so I've been using the Lens IDE to do my chart installs / upgrades instead of running helm from my shell.

I just ran `helm -n [namespace] get manifest [releasename]` but am not sure what I'm looking for in the output.  I don't see any reference to anything from the `mounts:` section, but I also don't see any references to the dynamic home directory mount defined in `singleuser: storage:` that is working fine.

I'm not sure what the right invocation for `helm template --debug` is.  I tried ` helm -n [namespace] template dask/daskhub --debug` but am getting this:

    Error: execution error at (daskhub/charts/jupyterhub/templates/proxy/deployment.yaml:28:32): Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!

**Comment by jacobtomlinson** [comment]
I think for the template debug you need to also pass your config file.

**Comment by tonycpsu** [comment]
@jacobtomlinson: thanks, found the `-f [values.yaml]` option for `helm template`, and not seeing the mounts in the output.

**Comment by consideRatio** [comment]
Using `helm template ./dask -f test.yaml` where `test.yaml` was like below, I conclude that passing values like this works as intended.

```yaml
jupyter:
  mounts:
    volumes:
      - name: project
        persistentVolumeClaim:
            claimName: claim-name
    volumeMounts:
      - name: project
        mountPath: /data


worker:
  mounts:
    volumes:
      - name: project
        persistentVolumeClaim:
            claimName: claim-name
    volumeMounts:
      - name: project
        mountPath: /data
```
