### ISSUE TITLE
Adding TLS/SSL to Dask Scheduler, Workers, and Jupyter

### ISSUE THREAD

**Issue by rileyhun** [dask/helm-chart#82]
**What happened**:
I am trying to add TLS/SSL Security to my Dask Cluster hosted on Google Kubernetes Engine, installed using helm. I added the fields to the config yaml file and then applied the changes to the Dask Cluster, but I'm still able to freely access my Dask cluster without having to add a security object. 

I'm trying to accomplish this in the documentation [1]

I also reviewed this similar issue [2] 

[1] https://distributed.dask.org/en/latest/tls.html
[2] https://github.com/dask/dask/issues/5079

While it is explained how to access a secured Dask cluster, there isn't much comprehensive information in the docs on how to add a security layer

**What you expected to happen**:
I was expecting to be prohibited from accessing the Dask cluster without invoking a security object, and then to be able to access the cluster when providing a security object

**Minimal Complete Verifiable Example**:

1. `helm repo add dask https://helm.dask.org`
2. Access k8s cluster
`gcloud container clusters get-credentials ${RELEASE} --region ${REGION}`
3. Install Dask workers
`helm install ${RELEASE} dask/dask --set scheduler.serviceType=LoadBalancer`
4. Create Security Files
`openssl req -newkey rsa:4096 -nodes -sha256 -x509 -days 3650 -nodes -out myca.pem -keyout mykey.pem`
5. Yaml File w/ Config Changes:

```
distributed:
  comm:
    default-scheme: tls
    require-encryption: True
    tls:
      ca-file: myca.pem
      scheduler:
        key: mykey.pem
        cert: myca.pem
      worker:
        key: mykey.pem
        cert: myca.pem
      client:
        key: mykey.pem
        cert: myca.pem

worker:
  name: worker
  allowed-failures: 5
  replicas: 10
  resources:
    limits:
      cpu: 2
      memory: 10G
    requests:
      cpu: 2
      memory: 10G
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray joblib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: >
        s3fs dask-ml pandas lz4 numpy dask distributed gcsfs SQLAlchemy google-cloud-storage pyarrow mlflow keras
        tensorflow prefect aiofile aiohttp asyncio gcloud-aio-storage pyspark --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray matplotlib joblib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: >
        s3fs dask-ml pandas lz4 numpy dask distributed gcsfs SQLAlchemy google-cloud-storage pyarrow mlflow keras
        tensorflow prefect aiofile aiohttp asyncio gcloud-aio-storage pyspark --upgrade

scheduler:
  allowed-failures: 5
  env:
    - name: EXTRA_PIP_PACKAGES
      value: >
        s3fs dask-ml pandas lz4 numpy dask distributed gcsfs SQLAlchemy google-cloud-storage pyarrow mlflow keras
        tensorflow prefect aiofile aiohttp asyncio gcloud-aio-storage pyspark --upgrade
```

6. Apply Config Changes
`helm upgrade ${RELEASE} dask/dask -f dask_config.yaml --set scheduler.serviceType=LoadBalancer --version 4.1.0`

**Anything else we need to know?**:
N/A

**Environment**:

- Dask version: 2.21
- Python version: 3.7.4
- Operating System: macOSX
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
You appear to be conflating the Dask configuration files with the helm chart configuration files.

In order to provide configuration to the scheduler you will need to specify [configuration](https://docs.dask.org/en/latest/configuration.html) as environment variables, something like this.

```yaml
scheduler:
  env:
    DASK_DISTRIBUTED__COMM__DEFAULT_SCHEME: "tls"
```

We could also explore allowing extra config as a config map which is mounted as a volume. **This does not exist today** but could look something like this.

```yaml
scheduler:
  extra_config:
    distributed:
      comm:
        default-scheme: tls
        require-encryption: True
        tls:
          ca-file: myca.pem
          scheduler:
            key: mykey.pem
            cert: myca.pem
          worker:
            key: mykey.pem
            cert: myca.pem
          client:
            key: mykey.pem
            cert: myca.pem
```

**Comment by jacobtomlinson** [comment]
That sounds like a helm problem. I would delete the release and install it again.

**Comment by jacobtomlinson** [comment]
Also that `True` should probably be `"true"`.

**Comment by rileyhun** [comment]
Thanks so much @jacobtomlinson, 

That seems to have done the trick in terms of the deployment. Will now test out the connection. 

Really appreciate the support. Been trying to figure this out for a couple days!

**Comment by rileyhun** [comment]
@jacobtomlinson 

I tried connecting to the scheduler as follows:

```
import dask.dataframe as dd
from dask.distributed import Client
from distributed.security import Security

sec = Security(tls_ca_file='myca.pem',
               tls_client_cert='myca.pem',
               tls_client_key='mykey.pem',
               require_encryption=True)

with Client("<scheduler_ip>:8786", security=sec) as dask_client:
    ddf = dd.read_csv('gs://<bucket_name>/my_file.csv',
                      engine='python',
                      error_bad_lines=False,
                      encoding="utf-8",
                      assume_missing=True
                      )

    print(ddf.shape[0].compute())

```
The connection doesn't seem to be working. 



```
RuntimeError: encryption required by Dask configuration, refusing communication from/to 'tcp://<scheduler_ip>:8786'
```

**Comment by jacobtomlinson** [comment]
You may need to specify `tls://` before the scheduler IP.

**Comment by rileyhun** [comment]
> You may need to specify `tls://` before the scheduler IP.

Thanks for the prompt response. Tried that and got a timeout error.

```
OSError: Timed out trying to connect to 'tls://<scheduler_ip>:8786' after 10 s: Timed out trying to connect to 'tls://<scheduler_ip>:8786' after 10 s: in <distributed.comm.tcp.TLSConnector object at 0x11d5aab90>: ConnectionRefusedError: [Errno 61] Connection refused
```

**Comment by jacobtomlinson** [comment]
Do the cert files exist in the workers? You'll need to ensure they are baked into your docker image, mounted as a volume or pulled in dynamically.

**Comment by rileyhun** [comment]
> Do the cert files exist in the workers? You'll need to ensure they are baked into your docker image, mounted as a volume or pulled in dynamically.

Thanks so much @jacobtomlinson. Finally got it working. Thanks a million for your help!

**Comment by rileyhun** [comment]
@jacobtomlinson 

Sorry - false alarm - encountered an issue. It seems to be stalling, and when I check the logs, it appears as though the scheduler isn't able to connect to the workers.

```
distributed.worker - INFO - Waiting to connect to: tcp://dask-gke-scaled-scheduler:8786
distributed.worker - INFO - Waiting to connect to: tcp://dask-gke-scaled-scheduler:8786
distributed.worker - INFO - Waiting to connect to: tcp://dask-gke-scaled-scheduler:8786
distributed.worker - INFO - Waiting to connect to: tcp://dask-gke-scaled-scheduler:8786
distributed.worker - INFO - Waiting to connect to: tcp://dask-gke-scaled-scheduler:8786
distributed.worker - INFO - Waiting to connect to: tcp://dask-gke-scaled-scheduler:8786
distributed.worker - INFO - Waiting to connect to: tcp://dask-gke-scaled-scheduler:8786
distributed.worker - INFO - Waiting to connect to: tcp://dask-gke-scaled-scheduler:8786
```

**Comment by jacobtomlinson** [comment]
Hmm it still looks like the workers are not speaking TLS.

```
distributed.worker - INFO - Waiting to connect to: tcp://dask-gke-scaled-scheduler:8786
```

Have you also configured the workers to use TLS?

```yaml
worker:
  env:
    - name: DASK_DISTRIBUTED__COMM__DEFAULT_SCHEME
      value: "tls"
    - name: DASK_DISTRIBUTED__COMM__REQUIRE_ENCRYPTION
      value: True
    - name: DASK_DISTRIBUTED__COMM__TLS__CA_FILE
      value: "myca.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__SCHEDULER__KEY
      value: "mykey.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__SCHEDULER__CERT
      value: "myca.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__WORKER__KEY
      value: "mykey.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__WORKER__CERT
      value: "myca.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__KEY
      value: "mykey.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__CERT
      value: "myca.pem"
```

**Comment by rileyhun** [comment]
Thanks @jacobtomlinson!

I can confirm that it works for the most part now - thanks so much. Looks like the only error I'm getting now is that it's upgrading my workers and schedulers to have python 3.8 even though I specified 3.7 in the dockerfile. 

As such, I'm getting this serialization error when trying to read a csv file using pandas. 

```
distributed.protocol.pickle - INFO - Failed to deserialize b"\x80\x05\x95}\x03\x00\x00\x00\x00\x00\x00\x8c\x15distributed.scheduler\x94\x8c\x0cKilledWorker\x94\x93\x94\x8c0('read-csv-103f2c7072b6bd6d354e88139bbbecd1', 1)\x94h\x00\x8c\x0bWorkerState\x94\x93\x94)\x81\x94N}\x94(\x8c\x06actors\x94\x8f\x94\x8c\x07address\x94\x8c\x16tls://10.32.5.11:44765\x94\x8c\tbandwidth\x94J\x00\xe1\xf5\x05\x8c\x05extra\x94}\x94\x8c\x08has_what\x94\x8f\x94\x8c\tlast_seen\x94K\x00\x8c\x0flocal_directory\x94\x8c4/dask-worker-space/dask-worker-space/worker-mad2zdny\x94\x8c\x0cmemory_limit\x94\x8a\x05\x00\xe0\x0bT\x02\x8c\x07metrics\x94}\x94\x8c\x04name\x94\x8c\x16tls://10.32.5.11:44765\x94\x8c\x05nanny\x94\x8c\x16tls://10.32.5.11:44171\x94\x8c\x06nbytes\x94K\x00\x8c\x08nthreads\x94K\x02\x8c\toccupancy\x94K\x00\x8c\x03pid\x94M\xe3\x02\x8c\nprocessing\x94\x8f\x94(\x8c0('read-csv-103f2c7072b6bd6d354e88139bbbecd1', 0)\x94\x8c0('read-csv-103f2c7072b6bd6d354e88139bbbecd1', 2)\x94h\x03\x8c0('read-csv-103f2c7072b6bd6d354e88139bbbecd1', 5)\x94\x8c0('read-csv-103f2c7072b6bd6d354e88139bbbecd1', 3)\x94\x8c0('read-csv-103f2c7072b6bd6d354e88139bbbecd1', 4)\x94\x90\x8c\tresources\x94}\x94\x8c\x08services\x94}\x94\x8c\tdashboard\x94M-\x81s\x8c\x07_status\x94\x8c\x10distributed.core\x94\x8c\x06Status\x94\x93\x94\x8c\x07running\x94\x85\x94R\x94\x8c\ntime_delay\x94K\x00\x8c\x0eused_resources\x94}\x94\x8c\x08versions\x94}\x94u\x86\x94b\x86\x94R\x94}\x94(\x8c\x04task\x94h\x03\x8c\x0blast_worker\x94h\x06ub."
Traceback (most recent call last):
  File "/Users/rihun/anaconda3/envs/dask-kubernetes/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 67, in loads
    return pickle.loads(x)
ValueError: unsupported pickle protocol: 5
```

Thanks again for your help - I am thrilled that I now have TLS/SSL authentication integrated!

**Comment by rileyhun** [comment]
Okay, can confirm that everything is working as expected. 

Once again, @jacobtomlinson, many thanks for your assistance. I shall now close this issue.

**Comment by jacobtomlinson** [comment]
Would you mind sharing your final config? I think we should add this as an example to the docs and your config would be a great starting point.

**Comment by rileyhun** [comment]
Absolutely! Here you go - 

Dockerfile
```
FROM daskdev/dask

RUN conda install --yes \
    -c conda-forge \
    python==3.7

ADD certs /certs/

ENTRYPOINT ["tini", "-g", "--", "/usr/bin/prepare.sh"]
```

helm config
```
worker:
  name: worker
  image:
    repository: "gcr.io/PROJECT_ID/mydask"
    tag: "latest"
  allowed-failures: 5
  replicas: 1
  resources:
    limits:
      cpu: 2
      memory: 10G
    requests:
      cpu: 2
      memory: 10G
  env:
    - name: DASK_DISTRIBUTED__COMM__DEFAULT_SCHEME
      value: "tls"
    - name: DASK_DISTRIBUTED__COMM__REQUIRE_ENCRYPTION
      value: "true"
    - name: DASK_DISTRIBUTED__COMM__TLS__CA_FILE
      value: "certs/myca.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__SCHEDULER__KEY
      value: "certs/mykey.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__SCHEDULER__CERT
      value: "certs/myca.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__WORKER__KEY
      value: "certs/mykey.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__WORKER__CERT
      value: "certs/myca.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__KEY
      value: "certs/mykey.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__CERT
      value: "certs/myca.pem"
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray joblib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: >
        s3fs dask-ml pandas lz4 numpy dask distributed gcsfs SQLAlchemy google-cloud-storage pyarrow mlflow keras
        tensorflow prefect aiofile aiohttp asyncio gcloud-aio-storage pyspark --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  serviceType: LoadBalancer
  password: 'sha1:db0c6a94bc10:d3c610e96988191aa6274a50aa659664e35e6946'
  enabled: true
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray matplotlib joblib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: >
        s3fs dask-ml pandas lz4 numpy dask distributed gcsfs SQLAlchemy google-cloud-storage pyarrow mlflow keras
        tensorflow prefect aiofile aiohttp asyncio gcloud-aio-storage pyspark --upgrade

scheduler:
  image:
    repository: "gcr.io/PROJECT_ID/mydask"
    tag: "latest"
  serviceType: LoadBalancer
  allowed-failures: 5
  env:
    - name: DASK_DISTRIBUTED__COMM__DEFAULT_SCHEME
      value: "tls"
    - name: DASK_DISTRIBUTED__COMM__REQUIRE_ENCRYPTION
      value: "true"
    - name: DASK_DISTRIBUTED__COMM__TLS__CA_FILE
      value: "certs/myca.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__SCHEDULER__KEY
      value: "certs/mykey.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__SCHEDULER__CERT
      value: "certs/myca.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__WORKER__KEY
      value: "certs/mykey.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__WORKER__CERT
      value: "certs/myca.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__KEY
      value: "certs/mykey.pem"
    - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__CERT
      value: "certs/myca.pem"
    - name: EXTRA_PIP_PACKAGES
      value: >
        s3fs dask-ml pandas lz4 numpy dask distributed gcsfs SQLAlchemy google-cloud-storage pyarrow mlflow keras
        tensorflow prefect aiofile aiohttp asyncio gcloud-aio-storage pyspark --upgrade
```

**Comment by marstival** [comment]
@rileyhun awesome. That works fine. 
Would be possible to avoid adding the ca/key files into the docker image? Perhaps, referencing  a kubernetes.io/tls certificate previously configured in the cluster as follows?
 ```sh
kubectl create secret tls my-tls-secret \
--key ca.key \
--cert ca.crt 
```
Thanks

**Comment by weiwang217** [comment]
I saw the same issue on my worker. The scheduler looks good. I have set up the config in the yaml file as follows. Any reason that only worker has this error @jacobtomlinson 
```yaml
      worker:
        replicas: 1
        spec:
          containers:
            - name: worker
              image: {{ .Values.imagePath }}
              args:
                - --mode=worker
                - --name=$(DASK_WORKER_NAME)
                - --worker_memory_limit=12GB
                - --worker_nthreads=1
                - --worker_nworkers=1
              ports:
                - name: http-dashboard
                  containerPort: 8788
                  protocol: TCP
              env:
                - name: NETRC
                  value: ""
                - name: OPENBLAS_NUM_THREADS
                  value: "1"
                - name: DASK_DISTRIBUTED__COMM__DEFAULT_SCHEME
                  value: "tls"
                - name: DASK_DISTRIBUTED__COMM__REQUIRE_ENCRYPTION
                  value: "true"
                - name: DASK_DISTRIBUTED__COMM__TLS__CA_FILE
                  value: "/tmp/ca_cert.pem"
                - name: DASK_DISTRIBUTED__COMM__TLS__SCHEDULER__KEY
                  value: "/tmp/private_key.pem"
                - name: DASK_DISTRIBUTED__COMM__TLS__SCHEDULER__CERT
                  value: "/tmp/cert.pem"
                - name: DASK_DISTRIBUTED__COMM__TLS__WORKER__KEY
                  value: "/tmp/private_key.pem"
                - name: DASK_DISTRIBUTED__COMM__TLS__WORKER__CERT
                  value: "/tmp/cert.pem"
                - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__KEY
                  value: "/tmp/private_key.pem"
                - name: DASK_DISTRIBUTED__COMM__TLS__CLIENT__CERT
                  value: "/tmp/cert.pem"
                - name: DASK_DISTRIBUTED__COMM__TIMEOUTS__CONNECT
                  value: "60s"
                - name: DASK_DISTRIBUTED__WORKER__USE_FILE_LOCKING
                  value: "False"
                - name: DASK_TEMPORARY_DIRECTORY
                  value: "/tmp"
              volumeMounts:
                - name: tmp
                  mountPath: "/tmp"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 10001
                runAsGroup: 10001
          volumes:
            - name: tmp
              emptyDir: {}
``` 

args)
I1012 18:15:16.970516 7557915392 main.py:321] File "/app/src/main/pipelines/lift_dask/lift_dask_image.binary.runfiles/pip_distributed/site-packages/distributed/comm/tcp.py", line 553, in __init__
I1012 18:15:16.971338 7557915392 main.py:321] self._check_encryption(address, connection_args)
I1012 18:15:16.971471 7557915392 main.py:321] File "/app/src/main/pipelines/lift_dask/lift_dask_image.binary.runfiles/pip_distributed/site-packages/distributed/comm/tcp.py", line 413, in _check_encryption
I1012 18:15:16.972165 7557915392 main.py:321] raise RuntimeError(
I1012 18:15:16.972285 7557915392 main.py:321] RuntimeError: encryption required by Dask configuration, refusing communication from/to 'tcp://'
