### ISSUE TITLE
Setup ingress for dask WebUI

### ISSUE THREAD

**Issue by zonca** [dask/helm-chart#9]
I am deploying this on Jetstream, I would like to expose the dask WebUI via Ingress.

In the same Kubernetes deployment I also have JupyterHub configured with zero-to-jupyterhub (with TLS provided by `kube-lego`.

In ingress, if I just replace `proxy-public` from `jupyterhub` with `dask-scheduler`, it works fine and I can browse the webUI, so the pod and the `LoadBalancer` work fine:

```
spec:
  rules:
  - host: js-xxx-xxx.jetstream-cloud.org
    http:
      paths:
      - backend:
          serviceName: dask-scheduler
          servicePort: 80
        path: /
  tls:
  - hosts:
    - js-xxx-xxx.jetstream-cloud.org
    secretName: kubelego-tls-jupyterhub
```

I would like however to have Jupyterhub on `/` and dask on `/dask`, I have tried with no success several variations of this, I always get 404 on `/dask`:

```
spec:
  rules:
  - host: js-xxx-xxx.jetstream-cloud.org
    http:
      paths:
      - backend:
          serviceName: proxy-public
          servicePort: 80
        path: /
      - backend:
          serviceName: dask-scheduler
          servicePort: 80
        path: /dask
  tls:
  - hosts:
    - js-xxx-xxx.jetstream-cloud.org
    secretName: kubelego-tls-jupyterhub
```

Would you have any suggestion? or do you know where I can ask for help?
